services:
  db:
    image: postgres:17-alpine
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: secret
    volumes:
      - pg_volume:/dev/shm
volumes:
  pg_volume: